### PR TITLE
Added AWS example

### PR DESCRIPTION
**Pull request by kgoedecke**
This AWS example uses Cloudify DSL 1.2 and works on AWS with Ubuntu 14.04 as of 04/26/16.

### CODE REVIEW

**Comment by EarthmanT** [comment]
I've made some changes. Here's the patch. 
[0001-making-more-universal.patch.txt](https://github.com/cloudify-examples/cloudify-kubernetes/files/244277/0001-making-more-universal.patch.txt)

**Comment by kgoedecke** [comment]
Let me review it so I can update my PR and then we can merge it into master.

**Comment by kgoedecke** [comment]
I fixed this, see https://github.com/kgoedecke/cloudify-kubernetes/commit/50e61e03ba28e3d52b4235820755337e4288f9ba

@dfilppi @EarthmanT I think we can merge this into master now!

**Comment by kgoedecke** [comment]
@EarthmanT thanks for merging my PR. I noticed that @dfilppi changed the overall structure during the last couple of days, as you already mentioned when we talked. I'll try to adjust the AWS example to match the new structure by the end of the week.

**Pull request merged**
